### ISSUE TITLE
Not a Keras tensor 

### ISSUE THREAD

**Issue by totuta** [kevinzakka/style_transfer#1]
Hi, I tried the below and got:

      $ python generate.py examples/bases/chicago.jpg examples/styles/umbrella_girl.jpg examples/results/
      Using Theano backend.

      Initializing Neural Style model...

      	Resizing images...
      	Size of content image is: (1, 474, 712, 3)
      	Size of style image is: (1, 474, 712, 3)
      	Size of output image is: (1, 474, 712, 3)
      Traceback (most recent call last):
        File "generate.py", line 83, in <module>
          main()
        File "generate.py", line 77, in main
          iterations)
        File "/Users/wonchang/Desktop/Research/_learn/style_transfer/neural_styler.py", line 102, in __init__
          self.dims = K.int_shape(self.input_img)
        File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 128, in int_shape
          raise Exception('Not a Keras tensor:', x)
      Exception: ('Not a Keras tensor:', Join.0)

What's happening?

**Comment by usernaamee** [comment]
@totuta 
I got the same error when I was using keras with theano backend.
With tensorflow backend, I was able to run it.

**Comment by kevinzakka** [comment]
Will take a look asap!

**Comment by kevinzakka** [comment]
Ok, I've updated the code to work with Tensorflow, cheers.
