### ISSUE TITLE
IOError: cannot identify image file 'input.jpg'

### ISSUE THREAD

**Issue by usernaamee** [kevinzakka/style_transfer#2]
Running `python generate.py input.jpg picaso-ww.jpg output.jpg` produces following error message:
```
Traceback (most recent call last):
  File "generate.py", line 2, in <module>
    from neural_styler import Neural_Styler
  File "/home/omega-desktop/codeplayground/style_transfer/neural_styler.py", line 6, in <module>
    from scipy.misc import imsave
ImportError: cannot import name imsave
```

**Comment by usernaamee** [comment]
Installing `PIL` or `Pillow` resolved the issue.
